apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: k0ivkyb55-go 
  janus-idp.io/tekton: k0ivkyb55-go
  backstage.io/kubernetes-id: k0ivkyb55-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k0ivkyb55-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  